### PR TITLE
replace localhost with 127.0.0.1 to get system tests to run on Node 18 correctly

### PR DESCRIPTION
**Pull request by philvarner**
**Related Issue(s):** 

- n/a

**Proposed Changes:**

1. Change uses of localhost to 127.0.0.1, since those cause failures with node 18 -- see https://github.com/node-fetch/node-fetch/issues/1624

**PR Checklist:**

- [X] I have added my changes to the [CHANGELOG](https://github.com/stac-utils/stac-server/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

### CODE REVIEW

**Review by gadomski — COMMENTED** [review]
I'm on macos and didn't have this problem:

```shell
$ npm run test:system
-- >8 --
  89 tests passed
```

Is there another test that is expected to fail on macos?

**Comment by philvarner** [comment]
I couldn't remember the details -- the issue is node 18 https://github.com/node-fetch/node-fetch/issues/1624

We recommend running with node 16, but using 127.0.0.1 works in either.

**Review by gadomski — APPROVED** [review]
> I couldn't remember the details -- the issue is node 18 https://github.com/node-fetch/node-fetch/issues/1624

Should we be setting `engines` w/ our tested+supported node versions? Since we don't test against 18, there could be other dragons, right?

**Comment by philvarner** [comment]
is `engines` in package.json? The default deploy uses the lambda Node 16 because 18 removes the built-in AWS SDK v2, which we depend upon, so this code won't run in an 18 lambda.

I have another PR in draft https://github.com/stac-utils/stac-server/pull/562 that upgrades everything to AWS SDK v3, but the tests were failing, I think because of this issue.

**Comment by gadomski** [comment]
> is engines in package.json?

Yup: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

**Pull request merged**
