### PR TITLE
Updates to AWS deployment and Paging

### LINKED ISSUE #55: Topics should be a list
According to the AWS CloudFormation [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-policy.html) AWS::SNS::TopicPolicy.Topics should be an array of strings. However, in the current serverless.yml, Topics is a single string.

### PR DESCRIPTION
**Pull request by aliasmrchips**
Fixes #55 which uncovered some other issues with `publishedTopicPolicy`, also fixed

### CODE REVIEW

**Comment by aliasmrchips** [comment]
Also fixes #58

**Comment by matthewhanson** [comment]
@aliasmrchips Thanks!  Sorry for the delay getting around to this. Can you change the PR to be against the develop branch? That's the latest. Once merged I'll cut a release and deploy to earth-search.

**Comment by matthewhanson** [comment]
@aliasmrchips Comparing this to develop it looks like there are already some equivalent changes. It appears as though I don't have the latest deployed to Earth-search.

**Comment by matthewhanson** [comment]
Fixed in develop, cutting release

**Pull request closed without merging**
