### PR TITLE
Fix a typo in a variable name

### PR DESCRIPTION
**Pull request by kurtmckee**
**Related Issue(s):** 

- N/A

**Proposed Changes:**

1. Fix typo in variable name: `exisiting` -> `existing`

**PR Checklist:**

- [x] I have added my changes to the [CHANGELOG](https://github.com/stac-utils/stac-server/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

### CODE REVIEW

**Review by philvarner — APPROVED** [review]

**Comment by kurtmckee** [comment]
@philvarner Something happened with my original commit, 0c7ed5f, which broke my commit signature and now marks the modified commit as "Unverified". The timeline in this PR suggests that this was a manual change that happened a few minutes before the PR was merged.

My account has vigilant mode enabled and these types of changes will result in a more uncertain commit history in the GitHub interface. Could you let me know what happened here?

**Comment by philvarner** [comment]
I think I did an "Update with rebase" from the GH UI.

**Comment by kurtmckee** [comment]
Ah, makes sense. If you encounter merge conflicts on PR's in the future, please give me an opportunity to fix that so the commit signatures remain intact. Thanks! :grinning:

**Comment by philvarner** [comment]
Will do. I'm going to look into vigilant mode, also.

**Comment by kurtmckee** [comment]
Nice! I started signing commits and tags six months ago and have tried to watch how that shows up in the GH interface. I only enabled vigilant mode last week and have found a few interesting corner cases.

What happened in this PR is new to me, but late last week I discovered that when I leave code suggestions in PR reviews -- and when the PR author commits those suggestions directly from the PR comment -- it shows up as "Partially verified" because I never actually committed anything! Instead, it's attributed to me by way of "Co-authored by" ([example](https://github.com/globus/globus-automate-client/commit/a48e199b159e62db384a4ec013120e0e80fc3ba3)).

Just wanted to share my experience so far. :+1:

**Pull request merged**
